AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Surnet::ParameterStore::Secret resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers.testEntrypoint
      Runtime: nodejs20.x
      CodeUri: ./
      Architectures:
        - arm64

  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers.entrypoint
      Runtime: nodejs20.x
      CodeUri: ./
      Architectures:
        - arm64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        